make:
	pdflatex --shell-escape *.tex slides/*.tex && pdflatex --shell-escape *.tex slides/*.tex
clean:
	rm -f *~ *.backup *.aux *.toc *.blg *.log *.out *.bbl *.dvi *.nav *.pyg *.snm *.lof slides/*~ slides/*.backup slides/*.aux slides/*.toc slides/*.blg slides/*.log slides/*.out slides/*.bbl slides/*.dvi slides/*.nav slides/*.pyg slides/*.snm slides/*.lof 2> /dev/null
